# looking to make changes? 
# drop me in ~/.config/wlxoverlay/settings.yaml
#

width: 0.3

size: [600, 700]

# +X: right, +Y: up, +Z: back
spawn_pos: [0, -0.1, -0.5]

elements:
  - type: Panel
    rect: [0, 0, 600, 800]
    bg_color: "#102030"

  - type: Label
    rect: [15, 35, 600, 70]
    font_size: 24
    fg_color: "#ffffff"
    source: Static
    text: Settings

  - type: Button
    rect: [560, 0, 40, 40]
    font_size: 16
    bg_color: "#880000"
    fg_color: "#ffffff"
    text: X
    click_down:
      - type: Window
        target: "settings"
        action: Destroy

  - type: Panel
    rect: [50, 53, 500, 1]
    bg_color: "#c0c0c0"

  ####### Watch Section #######

  - type: Label
    rect: [15, 85, 570, 24]
    font_size: 18
    fg_color: "#ffffff"
    source: Static
    text: Watch

  - type: Panel
    rect: [250, 105, 1, 100]
    bg_color: "#c0c0c0"

  - type: Label
    rect: [288, 105, 100, 24]
    font_size: 12
    fg_color: "#ffffff"
    source: Static
    text: Visibility

  - type: Button
    rect: [270, 120, 100, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#306060"
    text: "Hide"
    click_down:
      - type: Watch
        action: Hide

  - type: Button
    rect: [270, 170, 100, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#306060"
    text: "Swap Hand"
    click_down:
      - type: Watch
        action: SwitchHands

  - type: Panel
    rect: [390, 105, 1, 100]
    bg_color: "#c0c0c0"

  - type: Label
    rect: [430, 105, 120, 24]
    font_size: 12
    fg_color: "#ffffff"
    source: Static
    text: Watch Fade

  - type: Button
    rect: [410, 120, 140, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#306060"
    text: "Cutoff Point"
    click_down:
      - type: Toast
        message: Use stick up/down while hovering the button!
    scroll_up:
      - type: Watch
        action:
          ViewAngle: {kind: "MaxOpacity", delta: 0.01}
    scroll_down:
      - type: Watch
        action:
          ViewAngle: {kind: "MaxOpacity", delta: -0.01}

  - type: Button
    rect: [410, 170, 140, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#306060"
    text: "Cutoff Strength"
    click_down:
      - type: Toast
        message: Use stick up/down while hovering the button!
    scroll_up:
      - type: Watch
        action:
          ViewAngle: {kind: "MinOpacity", delta: 0.01}
    scroll_down:
      - type: Watch
        action: 
          ViewAngle: {kind: "MinOpacity", delta: -0.01}

  - type: Label
    rect: [25, 140, 90, 30]
    font_size: 12
    fg_color: "#ffffff"
    source: Static
    text: Rotation

  - type: Button
    rect: [108, 120, 30, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#306060"
    text: "X"
    click_down:
      - type: Toast
        message: Use stick up/down while hovering the button!
    scroll_up:
      - type: Watch
        action:
          Rotation: {axis: "X", delta: 0.25}
    scroll_down:
      - type: Watch
        action:
          Rotation: {axis: "X", delta: -0.25}

  - type: Button
    rect: [153, 120, 30, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#306060"
    text: "Y"
    click_down:
      - type: Toast
        message: Use stick up/down while hovering the button!
    scroll_up:
      - type: Watch
        action:
          Rotation: {axis: "Y", delta: 0.25}
    scroll_down:
      - type: Watch
        action:
          Rotation: {axis: "Y", delta: -0.25}

  - type: Button
    rect: [198, 120, 30, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#306060"
    text: "Z"
    click_down:
      - type: Toast
        message: Use stick up/down while hovering the button!
    scroll_up:
      - type: Watch
        action:
          Rotation: {axis: "Z", delta: 0.25}
    scroll_down:
      - type: Watch
        action:
          Rotation: {axis: "Z", delta: -0.25}

  - type: Label
    rect: [25, 190, 90, 30]
    font_size: 12
    fg_color: "#ffffff"
    source: Static
    text: Position

  - type: Button
    rect: [108, 170, 30, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#306060"
    text: "X"
    click_down:
      - type: Toast
        message: Use stick up/down while hovering the button!
    scroll_up:
      - type: Watch
        action:
          Position: {axis: "X", delta: 0.001}
    scroll_down:
      - type: Watch
        action:
          Position: {axis: "X", delta: -0.001}

  - type: Button
    rect: [153, 170, 30, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#306060"
    text: "Y"
    click_down:
      - type: Toast
        message: Use stick up/down while hovering the button!
    scroll_up:
      - type: Watch
        action:
          Position: {axis: "Y", delta: 0.001}
    scroll_down:
      - type: Watch
        action:
          Position: {axis: "Y", delta: -0.001}

  - type: Button
    rect: [198, 170, 30, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#306060"
    text: "Z"
    click_down:
      - type: Toast
        message: Use stick up/down while hovering the button!
    scroll_up:
      - type: Watch
        action:
          Position: {axis: "Z", delta: 0.001}
    scroll_down:
      - type: Watch
        action:
          Position: {axis: "Z", delta: -0.001}

  - type: Panel
    rect: [50, 220, 500, 1]
    bg_color: "#c0c0c0"

  ####### Mirror Section #######
  - type: Label
    rect: [15, 255, 570, 24]
    font_size: 18
    fg_color: "#ffffff"
    source: Static
    text: Mirrors

  - type: Label
    rect: [25, 290, 30, 30]
    font_size: 12
    fg_color: "#ffffff"
    source: Static
    text: M1

  - type: Button
    rect: [60, 270, 110, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#707070"
    text: "Show/Hide"
    click_down:
      - type: Window
        target: M1
        action: ShowMirror

  - type: Button
    rect: [185, 270, 60, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#707070"
    text: "Lock"
    click_down:
      - type: Overlay
        target: M1
        action: ToggleInteraction

  - type: Button
    rect: [258, 270, 30, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#880000"
    text: "X"
    click_down:
      - type: Window
        target: M1
        action: Destroy

  - type: Label
    rect: [25, 340, 30, 30]
    font_size: 12
    fg_color: "#ffffff"
    source: Static
    text: M2

  - type: Button
    rect: [60, 320, 110, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#707070"
    text: "Show/Hide"
    click_down:
      - type: Window
        target: M2
        action: ShowMirror

  - type: Button
    rect: [185, 320, 60, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#707070"
    text: "Lock"
    click_down:
      - type: Overlay
        target: M2
        action: ToggleInteraction

  - type: Button
    rect: [258, 320, 30, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#880000"
    text: "X"
    click_down:
      - type: Window
        target: M2
        action: Destroy

  - type: Label
    rect: [25, 390, 30, 30]
    font_size: 12
    fg_color: "#ffffff"
    source: Static
    text: M3

  - type: Button
    rect: [60, 370, 110, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#707070"
    text: "Show/Hide"
    click_down:
      - type: Window
        target: M3
        action: ShowMirror

  - type: Button
    rect: [185, 370, 60, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#707070"
    text: "Lock"
    click_down:
      - type: Overlay
        target: M3
        action: ToggleInteraction

  - type: Button
    rect: [258, 370, 30, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#880000"
    text: "X"
    click_down:
      - type: Window
        target: M3
        action: Destroy

  - type: Panel
    rect: [300, 240, 1, 200]
    bg_color: "#c0c0c0"

  ####### Color Gain Section #######

  - type: Label
    rect: [325, 255, 90, 24]
    font_size: 18
    fg_color: "#ffffff"
    source: Static
    text: Color Gain

  - type: Label
    rect: [470, 255, 90, 30]
    font_size: 12
    fg_color: "#ffffff"
    source: Static
    text: (SteamVR)

  - type: Button
    rect: [330, 270, 60, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#707070"
    text: "All"
    click_down:
      - type: Toast
        message: Use stick up/down while hovering the button!
    scroll_up:
      - type: ColorAdjust
        channel: All
        delta: 0.01
    scroll_down:
      - type: ColorAdjust
        channel: All
        delta: -0.01

  - type: Button
    rect: [405, 270, 30, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#701010"
    text: "R"
    click_down:
      - type: Toast
        message: Use stick up/down while hovering the button!
    scroll_up:
      - type: ColorAdjust
        channel: R
        delta: 0.01
    scroll_down:
      - type: ColorAdjust
        channel: R
        delta: -0.01

  - type: Button
    rect: [450, 270, 30, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#107010"
    text: "G"
    click_down:
      - type: Toast
        message: Use stick up/down while hovering the button!
    scroll_up:
      - type: ColorAdjust
        channel: G
        delta: 0.01
    scroll_down:
      - type: ColorAdjust
        channel: G
        delta: -0.01

  - type: Button
    rect: [495, 270, 30, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#101070"
    text: "B"
    click_down:
      - type: Toast
        message: Use stick up/down while hovering the button!
    scroll_up:
      - type: ColorAdjust
        channel: B
        delta: 0.01
    scroll_down:
      - type: ColorAdjust
        channel: B
        delta: -0.01

  - type: Panel
    rect: [325, 315, 225, 1]
    bg_color: "#c0c0c0"

  ####### Playspace Section #######

  - type: Label
    rect: [325, 345, 90, 24]
    font_size: 18
    fg_color: "#ffffff"
    source: Static
    text: Playspace

  - type: Button
    rect: [330, 360, 220, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#206060"
    text: "Fix Floor"
    click_down:
      - type: System
        action: PlayspaceFixFloor

  - type: Button
    rect: [330, 410, 220, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#206060"
    text: "Reset Offset"
    click_down:
      - type: System
        action: PlayspaceResetOffset

  ####### Notifications Section #######

  - type: Panel
    rect: [50, 460, 500, 1]
    bg_color: "#c0c0c0"

  - type: Label
    rect: [325, 490, 90, 24]
    font_size: 18
    fg_color: "#ffffff"
    source: Static
    text: Notifications

  - type: Button
    rect: [330, 505, 220, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#606020"
    text: "Enabled"
    click_down:
      - type: System
        action: ToggleNotifications

  - type: Button
    rect: [330, 555, 220, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#606020"
    text: "Sound Enabled"
    click_down:
      - type: System
        action: ToggleNotificationSounds

  - type: Panel
    rect: [50, 605, 500, 1]
    bg_color: "#c0c0c0"

  - type: Button
    rect: [330, 625, 220, 30]
    font_size: 12
    fg_color: "#ffffff"
    bg_color: "#206060"
    text: "Save Config"
    click_down:
      - type: System
        action: PersistConfig

